### ISSUE TITLE
Guidance on maptype, other parameters

### ISSUE THREAD

**Issue by camille-s** [mikey-harper/ggmapstyles#3]
I really appreciate this package. One thing that gave me trouble was recognizing the `get_googlemaps` arguments I'll need to pass along through `get_snazzymap`. This might be because I'm less familiar with what parts of the map tiles are & are not styled. For example, once first glance it wasn't clear to me that I should still assign `maptype = "roadmap"`. I thought there was some error that was getting me a terrain map, but it's just that the default shown on Snazzy maps is a roadmap, while the default from `get_googlemaps` is a terrain map, which is why they looked different. 

Not a problem with the package, but it might be helpful to include an example or two showing cases of passing arguments to `get_googlemaps`, particularly `maptype`, either in the readme or in the docs. I don't mind pitching in on crafting a couple examples. Thanks!

**Comment by dr-harper** [comment]
Hi @camille-s , thanks for this suggestion and glad to hear you are enjoying the package. It does seem like this would be useful to add, but I am currently slightly short of time so will not be able to do this right away. 

Your offer of crafting a few examples would be much appreciated! If you would like to help, feel free to submit a Pull Request, or you can add some text into this issue and I can add it to the documentation when I get a chance. 

Thanks!

**Comment by camille-s** [comment]
Cool, I'll mess around & come up with a couple examples.

**Comment by dr-harper** [comment]
Thanks again for this @camille-s, I just merged your request so will close this. Let me know if you have any other suggestions or features you would like to see :)
